### ISSUE TITLE
Automation

### ISSUE THREAD

**Issue by MaDXakeR039** [MaDXakeR039/badHost#6]
[Automatically move your cards](https://docs.github.com/articles/configuring-automation-for-project-boards/) to the right place based on the status and activity of your issues and pull requests.

**Comment by MaDXakeR039** [comment]
> [Automatically move your cards](https://docs.github.com/articles/configuring-automation-for-project-boards/) to the right place based on the status and activity of your issues and pull requests.

**Comment by MaDXakeR039** [comment]
67

**Comment by MaDXakeR039** [comment]
87

**Comment by MaDXakeR039** [comment]
76

**Comment by teomad** [comment]
> [Automatically move your cards](https://docs.github.com/articles/configuring-automation-for-project-boards/) to the right place based on the status and activity of your issues and pull requests.

**Comment by teomad** [comment]
> [Automatically move your cards](https://docs.github.com/articles/configuring-automation-for-project-boards/) to the right place based on the status and activity of your issues and pull requests.

Ok

**Comment by teomad** [comment]
Yes
